version: '3'

services:
  traefik:
    image: "traefik:v2.6"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "8105:80"
    networks:
      - app_net
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  landing-page-microfronted:
    build:
      context: landing-page/.
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.landing.rule=(PathPrefix(`/`))"
      - "traefik.http.services.landing.loadbalancer.server.port=80"
    networks:
      - app_net
  
  auth-page-microfronted:
    build:
      context: auth-page/.
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=(PathPrefix(`/authentication`))"
      - "traefik.http.services.auth.loadbalancer.server.port=80"
    networks:
      - app_net

  user-microservice:
    build:
      context: user-service/.
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.users-app.rule=(PathPrefix(`/users`))"
      - "traefik.http.routers.users-app.middlewares=users-stripprefix"
      - "traefik.http.middlewares.users-stripprefix.stripprefix.prefixes=/users/"
      - "traefik.http.services.users-app.loadbalancer.server.port=5000"
    networks:
      - app_net
      - user_net
    depends_on:
      - user_database
  
  parameter-microservice:
    build:
      context: parameters-service/.
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prarmeters-app.rule=(PathPrefix(`/parameters`))"
      - "traefik.http.routers.prarmeters-app.middlewares=parameters-stripprefix"
      - "traefik.http.middlewares.parameters-stripprefix.stripprefix.prefixes=/parameters/"
      - "traefik.http.services.prarmeters-app.loadbalancer.server.port=5000"
    networks:
      - app_net
      - parameter_net
    depends_on:
      - parameter_database

  ontology-microservice:
    build:
      context: ontology-service/.
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ontologies-app.rule=(PathPrefix(`/ontologies`))"
      - "traefik.http.routers.ontologies-app.middlewares=ontologies-stripprefix"
      - "traefik.http.middlewares.ontologies-stripprefix.stripprefix.prefixes=/ontologies/"
      - "traefik.http.services.prarmeters-app.loadbalancer.server.port=5000"
    networks:
      - app_net
    depends_on:
      - parameter_database

  parameter_database:
    image: postgres:latest
    environment:
      POSTGRES_DB: USER_DB
      POSTGRES_USER: USER_USER_DB
      POSTGRES_PASSWORD: USER_PASSWORD_ULTA_SECRETO
    networks:
      - parameter_net

  user_database:
    image: postgres:latest
    environment:
      POSTGRES_DB: USER_DB
      POSTGRES_USER: USER_USER_DB
      POSTGRES_PASSWORD: USER_PASSWORD_ULTA_SECRETO
    networks:
      - user_net

networks:
  app_net:
    driver: bridge
  user_net:
    driver: bridge
  parameter_net:
    driver: bridge