version: '3'

services:
  traefik:
    image: "traefik:v2.6"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "8105:80"
    networks:
      - app_net
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  host-page-microfronted:
    build:
      context: host-page/.
      dockerfile: Dockerfile
    ports:
      - "8106:4200"
    networks:
      - front_net

  landing-page-microfronted:
    build:
      context: landing-page/.
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.index-page-app.rule=(PathPrefix(`/index`))"
      - "traefik.http.services.index-page-app.loadbalancer.server.port=4200"
    networks:
      - front_net
  
  auth-page-microfronted:
    container_name: auth-page-container
    build:
      context: auth-page/.
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth-page-app.rule=(PathPrefix(`/auth`))"
      - "traefik.http.services.auth-page-app.loadbalancer.server.port=4200"
    networks:
      - front_net

  dashboard-page-microfronted:
    container_name: dashboard-page-container
    build:
      context: dashboard-page/.
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard-page-app.rule=(PathPrefix(`/dashboard`))"
      - "traefik.http.services.dashboard-page-app.loadbalancer.server.port=4200"
    networks:
      - front_net

  user-microservice:
    build:
      context: user-service/.
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.users-app.rule=(PathPrefix(`/users`))"
      - "traefik.http.routers.users-app.middlewares=users-stripprefix"
      - "traefik.http.middlewares.users-stripprefix.stripprefix.prefixes=/users/"
      - "traefik.http.services.users-app.loadbalancer.server.port=5000"
    networks:
      - app_net
  
  parameter-microservice:
    build:
      context: parameters-service/.
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prarmeters-app.rule=(PathPrefix(`/parameters`))"
      - "traefik.http.routers.prarmeters-app.middlewares=parameters-stripprefix"
      - "traefik.http.middlewares.parameters-stripprefix.stripprefix.prefixes=/parameters/"
      - "traefik.http.services.prarmeters-app.loadbalancer.server.port=5000"
    networks:
      - app_net

  ontology-microservice:
    build:
      context: ontology-service/.
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ontologies-app.rule=(PathPrefix(`/ontologies`))"
      - "traefik.http.routers.ontologies-app.middlewares=ontologies-stripprefix"
      - "traefik.http.middlewares.ontologies-stripprefix.stripprefix.prefixes=/ontologies/"
      - "traefik.http.services.prarmeters-app.loadbalancer.server.port=5000"
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
  front_net:
    driver: bridge